<a href="https://colab.research.google.com/github/mahesh9143/AnomalyDetection/blob/main/Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to the tensorflow fundementals

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


#create tensors with tf.constant

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


Create a vector

In [ ]:
vector = tf.constant([10,10])
vector.ndim

1

In [ ]:
vector2 = tf.constant([[10,10],[2,2]])
vector2.ndim

2

In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  2]], dtype=int32)>

In [ ]:
matrix = tf.constant([[10,10],[2,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  3]], dtype=int32)>

In [ ]:
matrix2 = tf.constant([[[10,10,1],[2,2,2],[1,1,1]]],dtype= tf.float16)
matrix2

<tf.Tensor: shape=(1, 3, 3), dtype=float16, numpy=
array([[[10., 10.,  1.],
        [ 2.,  2.,  2.],
        [ 1.,  1.,  1.]]], dtype=float16)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2.ndim

3

In [ ]:
matrix2[0][0][2]

<tf.Tensor: shape=(), dtype=float16, numpy=1.0>

In [ ]:
matrix2[0][0][2] = 4

TypeError: ignored

In [ ]:
matrix2[0][0][2].assign(4)

AttributeError: ignored

In [ ]:
matrix3 = tf.Variable([[[10,10,1],[2,2,2],[1,1,1]]],dtype= tf.float16)
matrix3

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=float16, numpy=
array([[[10., 10.,  1.],
        [ 2.,  2.,  2.],
        [ 1.,  1.,  1.]]], dtype=float16)>

In [ ]:
matrix3[0,0,2]

<tf.Tensor: shape=(), dtype=float16, numpy=1.0>

In [ ]:
m4 = tf.Variable([1,2])
m4

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
m4[1].assign(3)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 3], dtype=int32)>

In [ ]:
m4

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3], dtype=int32)>

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  3]], dtype=int32)>

In [ ]:
matrix[1][1]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

Random tensors

In [ ]:
import numpy as np

np.random.randn(1,6).reshape(3,2)

array([[-1.41151105, -0.55877404],
       [ 1.16682587,  1.30903507],
       [ 0.5685272 , -1.23855104]])

In [ ]:
np.linspace(1,7,10)

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

In [ ]:

np.linspace(0.5,10,20)


array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

# the random seed will make the random generator have same set of numbers

In [ ]:
r1 = tf.random.Generator.from_seed(42)
r1 = r1.normal(shape = (2,3))
r1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
r2 = tf.random.Generator.from_seed(42)
r2 = r2.normal(shape = (2,3))
r2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
r1 == r2

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

In [ ]:
r3 = tf.random.normal(shape= (2,3))
r3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.060304  , -0.49338198,  1.2646549 ],
       [ 0.14596353, -0.7172144 ,  0.2812531 ]], dtype=float32)>

In [ ]:
r1 == r3

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[False, False, False],
       [False, False, False]])>

In [ ]:
#now use the random seed to see the impact
r3 = tf.random.Generator.from_seed(42)
r3 = r3.normal(shape=(2,3))
r3

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
r1 == r3

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

In [ ]:
r2 == r3

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

In [5]:
#Shuffled and not shuffled tensors practice
import tensorflow as tf
import numpy as np
a = tf.random.Generator.from_seed(42)
a = a.normal(shape = (3,3),dtype = np.float16)

In [6]:
a

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-0.7563 , -0.06854,  0.0759 ],
       [-1.258  , -0.2319 , -1.811  ],
       [ 0.0999 , -0.51   , -0.7534 ]], dtype=float16)>

In [7]:
not_shuffled = a
shuffled = tf.random.shuffle(a)
not_shuffled,shuffled

(<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[-0.7563 , -0.06854,  0.0759 ],
        [-1.258  , -0.2319 , -1.811  ],
        [ 0.0999 , -0.51   , -0.7534 ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[-1.258  , -0.2319 , -1.811  ],
        [ 0.0999 , -0.51   , -0.7534 ],
        [-0.7563 , -0.06854,  0.0759 ]], dtype=float16)>)

In [10]:
tf.random.set_seed(42) #global seed #shuffled order is contiously shuffling though the seed is set 
tf.random.shuffle(a, seed = 42) # operation level seed

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-0.7563 , -0.06854,  0.0759 ],
       [-1.258  , -0.2319 , -1.811  ],
       [ 0.0999 , -0.51   , -0.7534 ]], dtype=float16)>

In [15]:

tf.random.shuffle(a) 

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-0.7563 , -0.06854,  0.0759 ],
       [ 0.0999 , -0.51   , -0.7534 ],
       [-1.258  , -0.2319 , -1.811  ]], dtype=float16)>

In [16]:
b = tf.random.Generator.from_seed(42)
b = b.normal(shape = (3,3),dtype = np.float16)
b

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-0.7563 , -0.06854,  0.0759 ],
       [-1.258  , -0.2319 , -1.811  ],
       [ 0.0999 , -0.51   , -0.7534 ]], dtype=float16)>

In [17]:
not_shuffled = b
shuffled = tf.random.shuffle(b)
not_shuffled,shuffled

(<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[-0.7563 , -0.06854,  0.0759 ],
        [-1.258  , -0.2319 , -1.811  ],
        [ 0.0999 , -0.51   , -0.7534 ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[-0.7563 , -0.06854,  0.0759 ],
        [ 0.0999 , -0.51   , -0.7534 ],
        [-1.258  , -0.2319 , -1.811  ]], dtype=float16)>)

In [19]:
tf.random.shuffle(b, seed = 42) 

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 0.0999 , -0.51   , -0.7534 ],
       [-0.7563 , -0.06854,  0.0759 ],
       [-1.258  , -0.2319 , -1.811  ]], dtype=float16)>

In [20]:
tf.random.shuffle(b, seed = 42) 

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 0.0999 , -0.51   , -0.7534 ],
       [-0.7563 , -0.06854,  0.0759 ],
       [-1.258  , -0.2319 , -1.811  ]], dtype=float16)>

In [41]:
tf.random.set_seed(42) #by using just the global seed in every run the shuffle order keeps intact in the below 3 steps 
# if global & operation seed used at the time then the order shuffle everytime as shown in the above steps
tf.random.shuffle(b) 

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-1.258  , -0.2319 , -1.811  ],
       [ 0.0999 , -0.51   , -0.7534 ],
       [-0.7563 , -0.06854,  0.0759 ]], dtype=float16)>

In [42]:
tf.random.set_seed(42)
tf.random.shuffle(b) 

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-1.258  , -0.2319 , -1.811  ],
       [ 0.0999 , -0.51   , -0.7534 ],
       [-0.7563 , -0.06854,  0.0759 ]], dtype=float16)>

In [43]:
tf.random.set_seed(42)
tf.random.shuffle(b) 

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[-1.258  , -0.2319 , -1.811  ],
       [ 0.0999 , -0.51   , -0.7534 ],
       [-0.7563 , -0.06854,  0.0759 ]], dtype=float16)>