<a href="https://colab.research.google.com/github/mahesh9143/AnomalyDetection/blob/main/Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to the tensorflow fundementals

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


#create tensors with tf.constant

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [6]:
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


Create a vector

In [8]:
vector = tf.constant([10,10])
vector.ndim

1

In [9]:
vector2 = tf.constant([[10,10],[2,2]])
vector2.ndim

2

In [10]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [11]:
vector2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  2]], dtype=int32)>

In [12]:
matrix = tf.constant([[10,10],[2,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  3]], dtype=int32)>

In [13]:
matrix2 = tf.constant([[[10,10,1],[2,2,2],[1,1,1]]],dtype= tf.float16)
matrix2

<tf.Tensor: shape=(1, 3, 3), dtype=float16, numpy=
array([[[10., 10.,  1.],
        [ 2.,  2.,  2.],
        [ 1.,  1.,  1.]]], dtype=float16)>

In [14]:
matrix.ndim

2

In [15]:
matrix2.ndim

3